### ISSUE TITLE
Can any one help with this issue

### ISSUE THREAD

**Issue by Megachuggayoshi** [brudin/Scooby#34]
![screen shot 2015-05-01 at 5 54 29 pm](https://cloud.githubusercontent.com/assets/10993521/7438544/7e31f94a-f02b-11e4-8ad3-a87fea12cdf9.png)

**Comment by brudin** [comment]
mind sharing ForgeModLoader-client-0.log?

**Comment by Megachuggayoshi** [comment]
Sorry in advance for the wall

2015-02-15 13:23:41 [INFO] [ForgeModLoader] Forge Mod Loader version 6.4.49.965 for Minecraft 1.6.4 loading
2015-02-15 13:23:41 [INFO] [ForgeModLoader] Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Mac OS X:x86_64:10.9.4, installed at /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Java classpath at launch is /Users/co3085/Library/Application Support/minecraft/libraries/net/minecraftforge/minecraftforge/9.11.1.965/minecraftforge-9.11.1.965.jar:/Users/co3085/Library/Application Support/minecraft/libraries/net/minecraft/launchwrapper/1.8/launchwrapper-1.8.jar:/Users/co3085/Library/Application Support/minecraft/libraries/org/ow2/asm/asm-all/4.1/asm-all-4.1.jar:/Users/co3085/Library/Application Support/minecraft/libraries/org/scala-lang/scala-library/2.10.2/scala-library-2.10.2.jar:/Users/co3085/Library/Application Support/minecraft/libraries/org/scala-lang/scala-compiler/2.10.2/scala-compiler-2.10.2.jar:/Users/co3085/Library/Application Support/minecraft/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar:/Users/co3085/Library/Application Support/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar:/Users/co3085/Library/Application Support/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar:/Users/co3085/Library/Application Support/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar:/Users/co3085/Library/Application Support/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar:/Users/co3085/Library/Application Support/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar:/Users/co3085/Library/Application Support/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar:/Users/co3085/Library/Application Support/minecraft/libraries/argo/argo/2.25_fixed/argo-2.25_fixed.jar:/Users/co3085/Library/Application Support/minecraft/libraries/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar:/Users/co3085/Library/Application Support/minecraft/libraries/com/google/guava/guava/14.0/guava-14.0.jar:/Users/co3085/Library/Application Support/minecraft/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar:/Users/co3085/Library/Application Support/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar:/Users/co3085/Library/Application Support/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:/Users/co3085/Library/Application Support/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:/Users/co3085/Library/Application Support/minecraft/libraries/com/google/code/gson/gson/2.2.2/gson-2.2.2.jar:/Users/co3085/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.0/lwjgl-2.9.0.jar:/Users/co3085/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.0/lwjgl_util-2.9.0.jar:/Users/co3085/Library/Application Support/minecraft/versions/1.6.4-Forge9.11.1.965/1.6.4-Forge9.11.1.965.jar
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Java library path at launch is /Users/co3085/Library/Application Support/minecraft/versions/1.6.4-Forge9.11.1.965/1.6.4-Forge9.11.1.965-natives-27677716492548
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Enabling runtime deobfuscation
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Instantiating coremod class FMLCorePlugin
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Enqueued coremod FMLCorePlugin
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Instantiating coremod class FMLForgePlugin
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Enqueued coremod FMLForgePlugin
2015-02-15 13:23:41 [FINE] [ForgeModLoader] All fundamental core mods are successfully located
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Discovering coremods
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Examining for coremod candidacy 1.6.4-SortFix-1.0.jar
2015-02-15 13:23:41 [FINEST] [ForgeModLoader] Adding 1.6.4-SortFix-1.0.jar to the list of known coremods, it will not be examined again
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Instantiating coremod class CorePlugin
2015-02-15 13:23:41 [WARNING] [ForgeModLoader] The coremod net.minecraftforge.lex.sortfix.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Enqueued coremod CorePlugin
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Examining for coremod candidacy CodeChickenLib-universal-1.6.4-1.0.0.62.jar
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Not found coremod data in CodeChickenLib-universal-1.6.4-1.0.0.62.jar
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Examining for coremod candidacy ForgeMultipart-universal-1.6.4-1.0.0.227.jar
2015-02-15 13:23:41 [FINEST] [ForgeModLoader] Found FMLCorePluginContainsFMLMod marker in ForgeMultipart-universal-1.6.4-1.0.0.227.jar, it will be examined later for regular @Mod instances
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Instantiating coremod class DepLoader
2015-02-15 13:23:41 [WARNING] [ForgeModLoader] The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Enqueued coremod DepLoader
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Examining for coremod candidacy WorldCore-universal-1.6.4-1.1.0.17.jar
2015-02-15 13:23:41 [FINEST] [ForgeModLoader] Adding WorldCore-universal-1.6.4-1.1.0.17.jar to the list of known coremods, it will not be examined again
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Instantiating coremod class WCFMLLoadingPlugin
2015-02-15 13:23:41 [WARNING] [ForgeModLoader] The coremod worldcore.asm.WCFMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Enqueued coremod WCFMLLoadingPlugin
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Examining for coremod candidacy Aroma1997Core MC.1.6.4 v.1.0.1.5.jar
2015-02-15 13:23:41 [FINEST] [ForgeModLoader] Found FMLCorePluginContainsFMLMod marker in Aroma1997Core MC.1.6.4 v.1.0.1.5.jar, it will be examined later for regular @Mod instances
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Instantiating coremod class CoreMod
2015-02-15 13:23:41 [WARNING] [ForgeModLoader] The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Enqueued coremod CoreMod
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Examining for coremod candidacy AromaBackup-1.6.4-0.0.0.0.1.jar
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Not found coremod data in AromaBackup-1.6.4-0.0.0.0.1.jar
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Examining for coremod candidacy BigReactors-0.3.3A.jar
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Not found coremod data in BigReactors-0.3.3A.jar
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Examining for coremod candidacy ChickenChunks 1.3.3.4.jar
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Not found coremod data in ChickenChunks 1.3.3.4.jar
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Examining for coremod candidacy CoFHCore-2.0.0.5.jar
2015-02-15 13:23:41 [FINEST] [ForgeModLoader] Found FMLCorePluginContainsFMLMod marker in CoFHCore-2.0.0.5.jar, it will be examined later for regular @Mod instances
2015-02-15 13:23:41 [FINE] [ForgeModLoader] Instantiating coremod class LoadingPlugin
2015-02-15 13:23:41 [WARNING] [ForgeModLoader] The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2015-02-15 13:23:42 [INFO] [STDERR] Warning: version of ForgeMultipart-universal-1.6.4-, 1.0.0.227 is newer than request 1.0.0.219
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Enqueued coremod LoadingPlugin
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy CodeChickenCore 0.9.0.9.jar
2015-02-15 13:23:42 [FINEST] [ForgeModLoader] Adding CodeChickenCore 0.9.0.9.jar to the list of known coremods, it will not be examined again
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Instantiating coremod class CodeChickenCorePlugin
2015-02-15 13:23:42 [WARNING] [ForgeModLoader] The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Enqueued coremod CodeChickenCorePlugin
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy Enchiridion-1.6.4-1.1.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Not found coremod data in Enchiridion-1.6.4-1.1.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy Evoc_1.0.0a.jar
2015-02-15 13:23:42 [FINEST] [ForgeModLoader] Adding Evoc_1.0.0a.jar to the list of known coremods, it will not be examined again
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Instantiating coremod class CoreDescription
2015-02-15 13:23:42 [WARNING] [ForgeModLoader] The coremod mcp.mobius.evoc.asm.CoreDescription does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Enqueued coremod CoreDescription
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy ExtraCells-1.6.9b.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Not found coremod data in ExtraCells-1.6.9b.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy Flatsigns-1.6.2-universal-1.4.0.15.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Not found coremod data in Flatsigns-1.6.2-universal-1.4.0.15.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy HQM-The Journey (4.0.6).jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Not found coremod data in HQM-The Journey (4.0.6).jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy HarvestCraftWaila-mc1.6.4-1.0.3.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Not found coremod data in HarvestCraftWaila-mc1.6.4-1.0.3.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy IguanaTweaks-1.6.4-prog7.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Not found coremod data in IguanaTweaks-1.6.4-prog7.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy InfiniBows-1.6.4-universal-coremod-1.2.0.14.jar
2015-02-15 13:23:42 [FINEST] [ForgeModLoader] Adding InfiniBows-1.6.4-universal-coremod-1.2.0.14.jar to the list of known coremods, it will not be examined again
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Instantiating coremod class LoadingPlugin
2015-02-15 13:23:42 [FINE] [ForgeModLoader] The coremod myrathi.infinibows.LoadingPlugin requested minecraft version 1.6.4 and minecraft is 1.6.4. It will be loaded.
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Enqueued coremod LoadingPlugin
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy InventoryTweaks-MC1.6.2-1.56-b77.jar
2015-02-15 13:23:42 [FINEST] [ForgeModLoader] Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-MC1.6.2-1.56-b77.jar, it will be examined later for regular @Mod instances
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Instantiating coremod class FMLPlugin
2015-02-15 13:23:42 [WARNING] [ForgeModLoader] The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Enqueued coremod FMLPlugin
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy JadedsBlood-1.6.4-Beta-1.0.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Not found coremod data in JadedsBlood-1.6.4-Beta-1.0.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy Mariculture-1.6.4-1.2.2f.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Not found coremod data in Mariculture-1.6.4-1.2.2f.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy MineFactoryReloaded-2.7.9-final.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Not found coremod data in MineFactoryReloaded-2.7.9-final.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy MobiusCore_1.2.1.jar
2015-02-15 13:23:42 [FINEST] [ForgeModLoader] Adding MobiusCore_1.2.1.jar to the list of known coremods, it will not be examined again
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Instantiating coremod class CoreDescription
2015-02-15 13:23:42 [WARNING] [ForgeModLoader] The coremod mcp.mobius.mobiuscore.asm.CoreDescription does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Enqueued coremod CoreDescription
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy ModTweaker-1.6.4-0.2a.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Not found coremod data in ModTweaker-1.6.4-0.2a.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy NEIPlugins-1.1.0.6.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Not found coremod data in NEIPlugins-1.1.0.6.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy Natura_mc1.6.X_2.1.14.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Not found coremod data in Natura_mc1.6.X_2.1.14.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy NetherOres-2.2.2-55.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Not found coremod data in NetherOres-2.2.2-55.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy NotEnoughItems 1.6.1.9.jar
2015-02-15 13:23:42 [FINEST] [ForgeModLoader] Adding NotEnoughItems 1.6.1.9.jar to the list of known coremods, it will not be examined again
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Instantiating coremod class NEICorePlugin
2015-02-15 13:23:42 [WARNING] [ForgeModLoader] The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Enqueued coremod NEICorePlugin
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy NotEnoughKeys-1.6.4-0.0.4.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy OpenBlocks-1.2.8.jar
2015-02-15 13:23:42 [FINEST] [ForgeModLoader] Found FMLCorePluginContainsFMLMod marker in OpenBlocks-1.2.8.jar, it will be examined later for regular @Mod instances
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Instantiating coremod class OpenBlocksCorePlugin
2015-02-15 13:23:42 [WARNING] [ForgeModLoader] The coremod openblocks.OpenBlocksCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Enqueued coremod OpenBlocksCorePlugin
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy OpenModsLib-0.5.jar
2015-02-15 13:23:42 [FINEST] [ForgeModLoader] Found FMLCorePluginContainsFMLMod marker in OpenModsLib-0.5.jar, it will be examined later for regular @Mod instances
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Instantiating coremod class OpenModsCorePlugin
2015-02-15 13:23:42 [WARNING] [ForgeModLoader] The coremod openmods.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Enqueued coremod OpenModsCorePlugin
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy PluginsforForestry-1.6.4-3.2.30-hotfix.jar
2015-02-15 13:23:42 [FINEST] [ForgeModLoader] Found FMLCorePluginContainsFMLMod marker in PluginsforForestry-1.6.4-3.2.30-hotfix.jar, it will be examined later for regular @Mod instances
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Instantiating coremod class PfFCoreMod
2015-02-15 13:23:42 [WARNING] [ForgeModLoader] The coremod denoflionsx.PluginsforForestry.Core.CoreMod.PfFCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Enqueued coremod PfFCoreMod
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy PowerCrystalsCore-1.1.8-9.jar
2015-02-15 13:23:42 [FINEST] [ForgeModLoader] Adding PowerCrystalsCore-1.1.8-9.jar to the list of known coremods, it will not be examined again
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Instantiating coremod class CoreLoader
2015-02-15 13:23:42 [FINE] [ForgeModLoader] The coremod powercrystals.core.CoreLoader requested minecraft version 1.6.4 and minecraft is 1.6.4. It will be loaded.
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Enqueued coremod CoreLoader
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy RedstoneArsenal-1.0.0.0.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Not found coremod data in RedstoneArsenal-1.0.0.0.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy SimplyJetpacks-0.3.0.0.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Not found coremod data in SimplyJetpacks-0.3.0.0.jar
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Examining for coremod candidacy TConstruct_mc1.6.4_1.5.5.7.jar
2015-02-15 13:23:42 [FINEST] [ForgeModLoader] Found FMLCorePluginContainsFMLMod marker in TConstruct_mc1.6.4_1.5.5.7.jar, it will be examined later for regular @Mod instances
2015-02-15 13:23:42 [FINE] [ForgeModLoader] Instantiating coremod class TConstructLoaderContainer
2015-02-15 13:23:43 [WARNING] [ForgeModLoader] The coremod tconstruct.preloader.TConstructLoaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2015-02-15 13:23:43 [INFO] [TCon-Preloader] Scalpel. Suction. Lumber axe. CLEAR! _zap_
2015-02-15 13:23:43 [INFO] [TCon-Preloader] Constructing preloader (Modules: [tconstruct.preloader.AccessTransformers, tconstruct.preloader.ASMInterfaceRepair])
2015-02-15 13:23:43 [INFO] [TCon-Preloader] Found a properties file. Attempting load...
2015-02-15 13:23:43 [INFO] [TCon-Preloader] Loaded properties successfully. Using specified settings.
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Enqueued coremod TConstructLoaderContainer
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Examining for coremod candidacy TMechworks_mc1.6.4_0.1.6.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Not found coremod data in TMechworks_mc1.6.4_0.1.6.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Examining for coremod candidacy TSteelworks-mc1.6.4_0.0.4.2-fix2.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Not found coremod data in TSteelworks-mc1.6.4_0.0.4.2-fix2.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Examining for coremod candidacy ThermalExpansion-3.0.0.7.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Not found coremod data in ThermalExpansion-3.0.0.7.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Examining for coremod candidacy TiCTooltips-mc1.6.4-1.1.7.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Not found coremod data in TiCTooltips-mc1.6.4-1.1.7.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Examining for coremod candidacy WailaHarvestability-mc1.6.4-1.0.2.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Not found coremod data in WailaHarvestability-mc1.6.4-1.0.2.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Examining for coremod candidacy Warp-Book-1.6.4-0.0.200c.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Not found coremod data in Warp-Book-1.6.4-0.0.200c.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Examining for coremod candidacy appeng-rv14-finale3-mc16x.jar
2015-02-15 13:23:43 [FINEST] [ForgeModLoader] Found FMLCorePluginContainsFMLMod marker in appeng-rv14-finale3-mc16x.jar, it will be examined later for regular @Mod instances
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Instantiating coremod class AppEngCore
2015-02-15 13:23:43 [WARNING] [ForgeModLoader] The coremod appeng.transformer.AppEngCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2015-02-15 13:23:43 [INFO] [ForgeModLoader] [AppEng] Core Init
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Enqueued coremod AppEngCore
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Examining for coremod candidacy autopackager-1.3.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Not found coremod data in autopackager-1.3.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Examining for coremod candidacy bdlib-mc164-1.2.2.45.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Not found coremod data in bdlib-mc164-1.2.2.45.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Examining for coremod candidacy binnie-mods-1.8.0.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Examining for coremod candidacy crowley-skyblock-v1.29e.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Examining for coremod candidacy denLib-1.6.4-3.2.6.jar
2015-02-15 13:23:43 [FINEST] [ForgeModLoader] Found FMLCorePluginContainsFMLMod marker in denLib-1.6.4-3.2.6.jar, it will be examined later for regular @Mod instances
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Instantiating coremod class denLibCore
2015-02-15 13:23:43 [WARNING] [ForgeModLoader] The coremod denoflionsx.denLib.CoreMod.denLibCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Enqueued coremod denLibCore
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Examining for coremod candidacy forestry-A-2.3.1.2-agskies.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Not found coremod data in forestry-A-2.3.1.2-agskies.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Examining for coremod candidacy gendustry-mc164-1.1.2.72.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Not found coremod data in gendustry-mc164-1.1.2.72.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Examining for coremod candidacy gtfoMicroblocks.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Not found coremod data in gtfoMicroblocks.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Examining for coremod candidacy jadedspawn-1.0.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Not found coremod data in jadedspawn-1.0.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Examining for coremod candidacy magicbees-2.1.13.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Not found coremod data in magicbees-2.1.13.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Examining for coremod candidacy neiaddons-mc164-1.10.5.70.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Not found coremod data in neiaddons-mc164-1.10.5.70.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Examining for coremod candidacy obsidiplates-1.6.2-universal-2.0.0.15.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Not found coremod data in obsidiplates-1.6.2-universal-2.0.0.15.jar
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Examining for coremod candidacy zMineTweaker-1.6.4-2.3.1.jar
2015-02-15 13:23:43 [FINEST] [ForgeModLoader] Found FMLCorePluginContainsFMLMod marker in zMineTweaker-1.6.4-2.3.1.jar, it will be examined later for regular @Mod instances
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Instantiating coremod class MineTweakerTransformer
2015-02-15 13:23:43 [FINE] [ForgeModLoader] The coremod stanhebben.minetweaker.transformer.MineTweakerTransformer requested minecraft version 1.6.4 and minecraft is 1.6.4. It will be loaded.
2015-02-15 13:23:43 [FINE] [ForgeModLoader] Enqueued coremod MineTweakerTransformer
2015-02-15 13:23:43 [INFO] [ForgeModLoader] Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
2015-02-15 13:23:43 [INFO] [ForgeModLoader] Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
2015-02-15 13:23:43 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
2015-02-15 13:23:43 [SEVERE] [ForgeModLoader] Unable to launch
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
    at java.util.ArrayList$Itr.remove(ArrayList.java:865)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

**Comment by brudin** [comment]
> Mod Loader version 6.4.49.965 for Minecraft 1.6.4 loading

Scooby isn't for this version, and nothing in this error log refers to Scooby.  I recommend you post on the Forge forums about this issue.
